// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package apiproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventServiceClient interface {
	SendEvent(ctx context.Context, opts ...grpc.CallOption) (EventService_SendEventClient, error)
	ExchangeConfig(ctx context.Context, in *AccessKey, opts ...grpc.CallOption) (*Config, error)
}

type eventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventServiceClient(cc grpc.ClientConnInterface) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) SendEvent(ctx context.Context, opts ...grpc.CallOption) (EventService_SendEventClient, error) {
	stream, err := c.cc.NewStream(ctx, &EventService_ServiceDesc.Streams[0], "/api.EventService/SendEvent", opts...)
	if err != nil {
		return nil, err
	}
	x := &eventServiceSendEventClient{stream}
	return x, nil
}

type EventService_SendEventClient interface {
	Send(*Event) error
	CloseAndRecv() (*EResponse, error)
	grpc.ClientStream
}

type eventServiceSendEventClient struct {
	grpc.ClientStream
}

func (x *eventServiceSendEventClient) Send(m *Event) error {
	return x.ClientStream.SendMsg(m)
}

func (x *eventServiceSendEventClient) CloseAndRecv() (*EResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(EResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *eventServiceClient) ExchangeConfig(ctx context.Context, in *AccessKey, opts ...grpc.CallOption) (*Config, error) {
	out := new(Config)
	err := c.cc.Invoke(ctx, "/api.EventService/ExchangeConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceServer is the server API for EventService service.
// All implementations must embed UnimplementedEventServiceServer
// for forward compatibility
type EventServiceServer interface {
	SendEvent(EventService_SendEventServer) error
	ExchangeConfig(context.Context, *AccessKey) (*Config, error)
	mustEmbedUnimplementedEventServiceServer()
}

// UnimplementedEventServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEventServiceServer struct {
}

func (UnimplementedEventServiceServer) SendEvent(EventService_SendEventServer) error {
	return status.Errorf(codes.Unimplemented, "method SendEvent not implemented")
}
func (UnimplementedEventServiceServer) ExchangeConfig(context.Context, *AccessKey) (*Config, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExchangeConfig not implemented")
}
func (UnimplementedEventServiceServer) mustEmbedUnimplementedEventServiceServer() {}

// UnsafeEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventServiceServer will
// result in compilation errors.
type UnsafeEventServiceServer interface {
	mustEmbedUnimplementedEventServiceServer()
}

func RegisterEventServiceServer(s grpc.ServiceRegistrar, srv EventServiceServer) {
	s.RegisterService(&EventService_ServiceDesc, srv)
}

func _EventService_SendEvent_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EventServiceServer).SendEvent(&eventServiceSendEventServer{stream})
}

type EventService_SendEventServer interface {
	SendAndClose(*EResponse) error
	Recv() (*Event, error)
	grpc.ServerStream
}

type eventServiceSendEventServer struct {
	grpc.ServerStream
}

func (x *eventServiceSendEventServer) SendAndClose(m *EResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *eventServiceSendEventServer) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _EventService_ExchangeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).ExchangeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EventService/ExchangeConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).ExchangeConfig(ctx, req.(*AccessKey))
	}
	return interceptor(ctx, in, info, handler)
}

// EventService_ServiceDesc is the grpc.ServiceDesc for EventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExchangeConfig",
			Handler:    _EventService_ExchangeConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendEvent",
			Handler:       _EventService_SendEvent_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api.proto",
}
